### ISSUE TITLE
PR не работает так как разные репозитории

### ISSUE THREAD

**Issue by Zar1official** [Saloed/softdev-2022-spring-task-3#10]
Оставляю ссылки тут
https://github.com/Zar1official/ChatApplication
https://github.com/Zar1official/ChatServer

**Comment by Saloed** [comment]
Т.к. комменты к коду в таком варианте оставлять сложно, то напишу только глобальные замечания:
1.  Нижние подчёркивания в именах пакетов лучше не использовать
2. С конфигом БД явно что-то не так
3. `ConnectedUser`  в котором есть `WebSocketSession` это не модель
4. `models` по хорошему нужно пошарить между проектами
